=== Aurjay/tracebackai-latest/src/components/database/data1jschema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_id": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string"
        }
      },
      "required": [
        "$oid"
      ]
    },
    "run_id": {
      "type": "string"
    },
    "artifacts": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "params": {
      "type": "object",
      "properties": {
        "bootstrap": {
          "type": "string"
        },
        "max_depth": {
          "type": "string"
        },
        "max_samples": {
          "type": "string"
        },
        "min_weight_fraction_leaf": {
          "type": "string"
        },
        "max_leaf_nodes": {
          "type": "string"
        },
        "class_weight": {
          "type": "string"
        },
        "min_samples_leaf": {
          "type": "string"
        },
        "random_state": {
          "type": "string"
        },
        "min_impurity_decrease": {
          "type": "string"
        },
        "verbose": {
          "type": "string"
        },
        "n_estimators": {
          "type": "string"
        },
        "criterion": {
          "type": "string"
        },
        "oob_score": {
          "type": "string"
        },
        "ccp_alpha": {
          "type": "string"
        },
        "warm_start": {
          "type": "string"
        },
        "max_features": {
          "type": "string"
        },
        "n_jobs": {
          "type": "string"
        },
        "min_samples_split": {
          "type": "string"
        }
      },
      "required": [
        "bootstrap",
        "max_depth",
        "max_samples",
        "min_weight_fraction_leaf",
        "max_leaf_nodes",
        "class_weight",
        "min_samples_leaf",
        "random_state",
        "min_impurity_decrease",
        "verbose",
        "n_estimators",
        "criterion",
        "oob_score",
        "ccp_alpha",
        "warm_start",
        "max_features",
        "n_jobs",
        "min_samples_split"
      ]
    },
    "metrics": {
      "type": "object",
      "properties": {
        "training_score": {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "type": "string"
            }
          },
          "required": [
            "$numberDouble"
          ]
        },
        "training_accuracy_score": {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "type": "string"
            }
          },
          "required": [
            "$numberDouble"
          ]
        },
        "training_precision_score": {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "type": "string"
            }
          },
          "required": [
            "$numberDouble"
          ]
        },
        "training_log_loss": {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "type": "string"
            }
          },
          "required": [
            "$numberDouble"
          ]
        },
        "training_f1_score": {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "type": "string"
            }
          },
          "required": [
            "$numberDouble"
          ]
        },
        "training_recall_score": {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "type": "string"
            }
          },
          "required": [
            "$numberDouble"
          ]
        },
        "training_roc_auc_score": {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "type": "string"
            }
          },
          "required": [
            "$numberDouble"
          ]
        }
      },
      "required": [
        "training_score",
        "training_accuracy_score",
        "training_precision_score",
        "training_log_loss",
        "training_f1_score",
        "training_recall_score",
        "training_roc_auc_score"
      ]
    },
    "tags": {
      "type": "object",
      "properties": {
        "estimator_class": {
          "type": "string"
        },
        "estimator_name": {
          "type": "string"
        }
      },
      "required": [
        "estimator_class",
        "estimator_name"
      ]
    }
  },
  "required": [
    "_id",
    "run_id",
    "artifacts",
    "params",
    "metrics",
    "tags"
  ]
}

=== Aurjay/tracebackai-latest/src/components/database/data1.json
{
  "_id": {
    "$oid": "634418bd8877bcc3cc229857"
  },
  "run_id": "eaddb2d09f754a32a53ee6930ba8a7b3",
  "artifacts": [
    "model/MLmodel",
    "model/conda.yaml",
    "model/model.pkl",
    "model/python_env.yaml",
    "model/requirements.txt"
  ],
  "params": {
    "bootstrap": "True",
    "max_depth": "None",
    "max_samples": "None",
    "min_weight_fraction_leaf": "0.0",
    "max_leaf_nodes": "None",
    "class_weight": "None",
    "min_samples_leaf": "1",
    "random_state": "None",
    "min_impurity_decrease": "0.0",
    "verbose": "0",
    "n_estimators": "100",
    "criterion": "gini",
    "oob_score": "False",
    "ccp_alpha": "0.0",
    "warm_start": "False",
    "max_features": "sqrt",
    "n_jobs": "None",
    "min_samples_split": "2"
  },
  "metrics": {
    "training_score": {
      "$numberDouble": "0.9803370786516854"
    },
    "training_accuracy_score": {
      "$numberDouble": "0.9803370786516854"
    },
    "training_precision_score": {
      "$numberDouble": "0.9803467902611981"
    },
    "training_log_loss": {
      "$numberDouble": "0.12479794969312225"
    },
    "training_f1_score": {
      "$numberDouble": "0.9803091088695799"
    },
    "training_recall_score": {
      "$numberDouble": "0.9803370786516854"
    },
    "training_roc_auc_score": {
      "$numberDouble": "0.9976595158827505"
    }
  },
  "tags": {
    "estimator_class": "sklearn.ensemble._forest.RandomForestClassifier",
    "estimator_name": "RandomForestClassifier"
  }

}
